export const products = [
  {
    id: "1",
    name: "Oatmeal Apple Pastry",
    price: "Rs. 350",
    description: "Freshly baked with organic apples and oats.",
    image: "/images/applepastery.jpg",
  },
  {
    id: "2",
    name: "Banana Walnut Muffin",
    price: "Rs. 280",
    description: "Soft, healthy, and made for seniors.",
    image: "/images/bananamuffin.jpg",
  },
  {
    id: "3",
    name: "Low-Sugar Carrot Cake",
    price: "Rs. 400",
    description: "Delicious, diabetic-friendly carrot cake.",
    image: "/images/lowsugarcake.jpg",
  },
  {
    id: "4",
    name: "Multigrain Raisin Bread",
    price: "Rs. 320",
    description: "Wholesome multigrain loaf with juicy raisins.",
    image: "/images/raisinbread.jpg",
  },
  {
    id: "5",
    name: "Chia Seed Cookies",
    price: "Rs. 220",
    description: "Crunchy cookies packed with chia goodness.",
    image: "/images/chiacookies.jpg",
  },

  {
    id: "7",
    name: "Almond Date Bites",
    price: "Rs. 300",
    description: "Sugar-free bites with natural sweetness.",
    image: "/images/almondbite.jpg",
  },
  {
    id: "8",
    name: "Pumpkin Spice Muffins",
    price: "Rs. 330",
    description: "Perfect flavor, light on the stomach.",
    image: "/images/pumpkinmuffin.jpg",
  },
  {
    id: "9",
    name: "Healthy Honey Granola Bars",
    price: "Rs. 250",
    description: "Great snack with nuts, oats, and honey.",
    image: "/images/granolabars.jpg",
  },
  {
    id: "10",
    name: "Puffed Rice Cake",
    price: "Rs. 260",
    description: "Light, chewy, and full of fiber.",
    image: "/images/puffincake.jpg",
  },
];
